# Generated by Django 3.0.4 on 2020-03-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=26, null=True)),
                ('state', models.CharField(max_length=26, null=True)),
                ('zip', models.CharField(max_length=6, null=True)),
                ('notes', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=26, null=True)),
                ('city', models.CharField(max_length=26, null=True)),
                ('state', models.CharField(max_length=26, null=True)),
                ('zip', models.CharField(max_length=6, null=True)),
                ('notes', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_manufacturer', models.CharField(max_length=50)),
            ],
        ),
    ]
